---
- hosts: all
  become: true
  become_user: root
  gather_facts: no
#creating variables
  vars:
    git_repo: https://github.com/Bimalkhimdung/weather-app-backend-aayulogic.git
    remote_dir: /home/devops/Test

 #all tasks are defined here
  tasks:
   - name: installing required packages
     apt:
       name:
         - git
         - python3-pip

   - name: pull repo from git-repository
     git:
        repo: "{{ git_repo}}"
        dest: "{{ remote_dir }}/"
        remote: origin
        version: test
        force: yes
        update: yes  #This will update file if already presents
   - name: Create virtual environment
     shell: python3 -m venv {{ remote_dir }}/env

   - name: changing permission for env
     file:
       path: "{{ remote_dir }}/env/bin/activate"
       owner: devops
       group: devops
       mode: "0755"
   - name: activating env and installing dependencies
     block:   #for executing block content once
       - name: activating env
         shell: |
          source {{ remote_dir }}/env/bin/activate
         args:
           executable: /bin/bash  #this command helps to execute source command
      # this sectioin is used for specifying the path of env
      # at remote server
         environment:
           PATH: "{{ansible_env.PATH}}"

       - name: making requirements executable
         file:
           path: "{{remote_dir}}/requirements.txt"
           mode: u+x
       - name: installing dependencies
         shell: pip install -r requirements.txt
         args:
           chdir: "{{remote_dir}}"
#
       - name: Run django Migration
         shell: |
          python3 manage.py migrate
         args:
          chdir: "{{remote_dir}}"

#       - name: feeding data
#         shell: python3 manage.py feed_data_to_model
#         args:
#          chdir: /home/devops/Test/

       - name:  start gunicorn server
         shell: /home/devops/Test/env/bin/gunicorn weather_app.wsgi:application --reload --bind 192.168.102.238:8000
         args:
           chdir: "{{ remote_dir}}"

