name: Deploy
on:
    # push: 
    #   branches:
    #     - none
    workflow_dispatch:

jobs:
    Deploying-and-Operating:
     runs-on: ubuntu-latest
  
     steps:
      - name: Code Check
        uses: actions/checkout@v2
      - name: Running script
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{secrets.AWS_HOST}}
          username: ubuntu
          port: 22
          key: ${{secrets.AWS_PRIVATE_KEY}}
          script: |
                  whoami 
                  ls 
